In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
from time import sleep
import re

#

In [3]:
HEADERS = {
    'User-Agent': 'qangos-scraper/1.0(contact:qangos.bsdsba2028@aim.edu)'
}


def request_site(
    url: str,
    headers: dict = HEADERS,
    sleep_time: int = 1,
    ignore_message: bool = False,
    params: dict = None
):
    """
    Execute GET request on specified url. Returns response
    """
    try:
        if not params:
            response = requests.get(url, headers=headers)
        else:
            response = requests.get(url, headers=headers, params=params)
        sleep(sleep_time)
        response.raise_for_status()
    except requests.RequestException as e:
        print("Failed to fetch page:", e)
    else:
        if not ignore_message:
            print(f"Page fetched! {url}")
    return response

In [4]:
ref_regex = re.compile(r'\[\d+\]')

def clean_item(item):
    return ref_regex.sub('', item)

def get_item(item, tag='title'):
    if not item.find('a'):
        if tag=='href':
            return None
        return clean_item(item.text.strip())

    if tag.lower() == 'href':
        if item.a['href'].startswith('#'):
            return None
        if not item.a['href'].startswith('/'):
            return None
        return clean_item(item.a['href'])

    if item.a.has_attr(tag):
        return clean_item(item.a['title'])

    return clean_item(item.text.strip())


def get_game_data(row):
    items = row.find_all('td')

    game = get_item(items[0])
    link = get_item(items[0], 'href')
    publisher = get_item(items[1])
    system = get_item(items[2])
    release = get_item(items[3])
    setting = get_item(items[4])

    return {
        'game': game,
        'link': link,
        'publisher': publisher,
        'system': system,
        'release_year': release,
        'setting': setting
    }

In [188]:
link = 'https://en.wikipedia.org/wiki/List_of_tabletop_role-playing_games'
page = request_site(link)
soup = BeautifulSoup(page.content)

Page fetched! https://en.wikipedia.org/wiki/List_of_tabletop_role-playing_games

In [196]:
games = []
for i in soup.tbody.find_all('tr')[1:]:
    # check if row info is complete, skip if not
    if len(i.find_all('td')) != 6:
        continue

    games.append(get_game_data(i))

In [199]:
games_df = pd.DataFrame(games)
games_df.head()

,game,link,publisher,system,release_year,setting
0,13th Age,/wiki/13th_Age,Pelgrane Press,D20 System,2013,High fantasy
1,The 23rd Letter,/wiki/The_23rd_Letter,Crucible Design,,1996,
2,2300 AD,/wiki/2300_AD,Game Designers' Workshop,,1989,Hard science fiction
3,3D&T,/wiki/3D%26T,Editora Talismã (formerly Trama Editorial),,1994,
4,7th Sea (role-playing game),/wiki/7th_Sea_(role-playing_game),Alderac Entertainment Group,D20 System,"1999, 2016",Pirate

In [244]:
def get_game_description(link):
    if not link:
        return None
        
    l = f'https://en.wikipedia.org/{link}'
    page = request_site(l)
    soup = BeautifulSoup(page.content)
    
    return clean_item(' '.join([p.text.strip() for p in soup.find_all('p')])).strip()

In [245]:
games_df['description'] = games_df['link'].apply(get_game_description)

Page fetched! https://en.wikipedia.org//wiki/13th_Age
Page fetched! https://en.wikipedia.org//wiki/The_23rd_Letter
Page fetched! https://en.wikipedia.org//wiki/2300_AD
Page fetched! https://en.wikipedia.org//wiki/3D%26T
Page fetched! https://en.wikipedia.org//wiki/7th_Sea_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Aberrant_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/ACE_Agents!
Page fetched! https://en.wikipedia.org//wiki/Active_Exploits
Page fetched! https://en.wikipedia.org//wiki/Editions_of_Dungeons_%26_Dragons#Advanced_Dungeons_&_Dragons
Page fetched! https://en.wikipedia.org//wiki/Advanced_Fighting_Fantasy
Page fetched! https://en.wikipedia.org//wiki/Adventure!_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Adventure!
Page fetched! https://en.wikipedia.org//wiki/Adventurers_Guild
Page fetched! https://en.wikipedia.org//wiki/Adventures_in_Fantasy
Page fetched! https://en.wikipedia.org//wiki/The_Adventures_of_Indiana_Jones_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Adventures_in_Middle-earth
Page fetched! https://en.wikipedia.org//wiki/After_the_Bomb_(game)
Page fetched! https://en.wikipedia.org//wiki/Aftermath!
Page fetched! https://en.wikipedia.org//wiki/Afterwars
Page fetched! https://en.wikipedia.org//wiki/Age_of_the_Tempest
Page fetched! https://en.wikipedia.org//wiki/Age_of_Ruin_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Agone
Page fetched! https://en.wikipedia.org//wiki/Albedo_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Alice_is_Missing
Page fetched! https://en.wikipedia.org//wiki/ALIEN:_The_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Aliens_Adventure_Game
Page fetched! https://en.wikipedia.org//wiki/All_Flesh_Must_Be_Eaten
Page fetched! https://en.wikipedia.org//wiki/All-Star_Wrestling_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Alma_Mater_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Alshard
Page fetched! https://en.wikipedia.org//wiki/Alshard#Alshard_GAIA
Page fetched! https://en.wikipedia.org//wiki/Alternity
Page fetched! https://en.wikipedia.org//wiki/Amazing_Engine
Page fetched! https://en.wikipedia.org//wiki/Amber_Diceless_Roleplaying
Page fetched! https://en.wikipedia.org//wiki/Anima:_Beyond_Fantasy
Page fetched! https://en.wikipedia.org//wiki/Angel_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Apocalypse_Keys
Page fetched! https://en.wikipedia.org//wiki/Apocalypse_World
Page fetched! https://en.wikipedia.org//wiki/Arcana_Unearthed
Page fetched! https://en.wikipedia.org//wiki/Archaeron
Page fetched! https://en.wikipedia.org//wiki/Arduin
Page fetched! https://en.wikipedia.org//wiki/Aria_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Arianrhod_RPG
Page fetched! https://en.wikipedia.org//wiki/Armageddon:_2089
Page fetched! https://en.wikipedia.org//wiki/Armageddon:_The_End_Times
Page fetched! https://en.wikipedia.org//wiki/Armored_Trooper_VOTOMS:_The_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Army_of_Darkness_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Ars_Magica
Page fetched! https://en.wikipedia.org//wiki/Artesia:_Adventures_in_the_Known_World
Page fetched! https://en.wikipedia.org//wiki/Ashen_Stars
Page fetched! https://en.wikipedia.org//wiki/Atlantis_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Atomic_Robo#Roleplaying_game
Page fetched! https://en.wikipedia.org//wiki/Attack_of_the_Humans
Page fetched! https://en.wikipedia.org//wiki/The_Authority_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Avatar_Legends:_The_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Babylon_5_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Badlands_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/BASH!_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Barony_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Basic_Fantasy_RPG
Page fetched! https://en.wikipedia.org//wiki/Basic_Role-Playing
Page fetched! https://en.wikipedia.org//wiki/Batman_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/BattleDragons
Page fetched! https://en.wikipedia.org//wiki/Battlelords_of_the_23rd_Century
Page fetched! https://en.wikipedia.org//wiki/Battlestar_Galactica_Role_Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Behind_Enemy_Lines_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Beyond_the_Supernatural
Page fetched! https://en.wikipedia.org//wiki/Bifrost_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Big_Bang_Comics_RPG
Page fetched! https://en.wikipedia.org//wiki/Big_Eyes,_Small_Mouth
Page fetched! https://en.wikipedia.org//wiki/Black_Crusade_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/The_Black_Sword_Hack
Page fetched! https://en.wikipedia.org//wiki/Blades_in_the_Dark
Page fetched! https://en.wikipedia.org//wiki/Blade_Runner:_The_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Blood_Dawn
Page fetched! https://en.wikipedia.org//wiki/Blood_of_Heroes_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Blue_Planet_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Blue_Rose_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Bluebeard%27s_Bride
Page fetched! https://en.wikipedia.org//wiki/Boot_Hill_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Brave_New_World_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Breaking_the_Ice_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Brindlewood_Bay
Page fetched! https://en.wikipedia.org//wiki/Bubblegum_Crisis_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Buccaneer_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Buck_Rogers_XXVC
Page fetched! https://en.wikipedia.org//wiki/Buffy_the_Vampire_Slayer_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Bullwinkle_and_Rocky_Role-Playing_Party_Game
Page fetched! https://en.wikipedia.org//wiki/Bunnies_and_Burrows
Page fetched! https://en.wikipedia.org//wiki/Bureau_13:_Stalking_the_Night_Fantastic
Page fetched! https://en.wikipedia.org//wiki/Roll20#Burn_Bryte
Page fetched! https://en.wikipedia.org//wiki/Burning_Empires_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/The_Burning_Wheel
Page fetched! https://en.wikipedia.org//wiki/Bushido_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/By_the_Gods
Page fetched! https://en.wikipedia.org//wiki/Cadillacs_and_Dinosaurs_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Cadwallon_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Call_of_Cthulhu_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Capes_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Cartoon_Action_Hour
Page fetched! https://en.wikipedia.org//wiki/Car_Wars
Page fetched! https://en.wikipedia.org//wiki/Cassiopean_Empire
Page fetched! https://en.wikipedia.org//wiki/Castles_%26_Crusades
Page fetched! https://en.wikipedia.org//wiki/Castle_Falkenstein_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/The_Castle_Perilous
Page fetched! https://en.wikipedia.org//wiki/Challengers_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Champions_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Changeling:_The_Dreaming
Page fetched! https://en.wikipedia.org//wiki/Changeling:_The_Lost
Page fetched! https://en.wikipedia.org//wiki/Children_of_the_Sun_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Chill_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Chivalry_%26_Sorcery
Page fetched! https://en.wikipedia.org//wiki/Chronicles_of_Ramlar
Page fetched! https://en.wikipedia.org//wiki/City_of_Mist
Page fetched! https://en.wikipedia.org//wiki/Commando_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Companions%27_Tale
Page fetched! https://en.wikipedia.org//wiki/Conan_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Conan:_Adventures_in_an_Age_Undreamed_Of
Page fetched! https://en.wikipedia.org//wiki/GURPS_Conan
Page fetched! https://en.wikipedia.org//wiki/Conan:_The_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/The_Confederate_Rangers
Page fetched! https://en.wikipedia.org//wiki/Conspiracy_X
Page fetched! https://en.wikipedia.org//wiki/Continuum_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Core_Command
Page fetched! https://en.wikipedia.org//wiki/Corporation_(rpg)
Page fetched! https://en.wikipedia.org//wiki/CORPS
Page fetched! https://en.wikipedia.org//wiki/Coyote_%26_Crow
Page fetched! https://en.wikipedia.org//wiki/Creeks_and_Crawdads
Page fetched! https://en.wikipedia.org//wiki/Crime_Fighter
Page fetched! https://en.wikipedia.org//wiki/Crimefighters
Page fetched! https://en.wikipedia.org//wiki/Crystalicum
Page fetched! https://en.wikipedia.org//wiki/CthulhuTech
Page fetched! https://en.wikipedia.org//wiki/Cutthroat:_The_Shadow_Wars
Page fetched! https://en.wikipedia.org//wiki/Cybergeneration
Page fetched! https://en.wikipedia.org//wiki/Cyberpunk_2013
Page fetched! https://en.wikipedia.org//wiki/Cyberpunk_2020
Page fetched! https://en.wikipedia.org//wiki/Cyberpunk_RED
Page fetched! https://en.wikipedia.org//wiki/Cyberspace_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Cyborg_Commando
Page fetched! https://en.wikipedia.org//wiki/D6_Adventure
Page fetched! https://en.wikipedia.org//wiki/D6_Fantasy
Page fetched! https://en.wikipedia.org//wiki/D6_Space
Page fetched! https://en.wikipedia.org//wiki/D6_System
Page fetched! https://en.wikipedia.org//wiki/D20_Future
Page fetched! https://en.wikipedia.org//wiki/D20_Modern
Page fetched! https://en.wikipedia.org//wiki/D20_Past
Page fetched! https://en.wikipedia.org//wiki/D20_System
Page fetched! https://en.wikipedia.org//wiki/Dallas_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Danger_International
Page fetched! https://en.wikipedia.org//wiki/Dangerous_Journeys
Page fetched! https://en.wikipedia.org//wiki/Daredevils_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dark_Ages_(World_of_Darkness)
Page fetched! https://en.wikipedia.org//wiki/Dark_Champions
Page fetched! https://en.wikipedia.org//wiki/Dark_Conspiracy
Page fetched! https://en.wikipedia.org//wiki/Dark_Dungeons_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/The_Dark_Eye_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dark_Heresy_(RPG)
Page fetched! https://en.wikipedia.org//wiki/Dark_Streets_(RPG)
Page fetched! https://en.wikipedia.org//wiki/Darwin%27s_World
Page fetched! https://en.wikipedia.org//wiki/Dawning_Star
Page fetched! https://en.wikipedia.org//wiki/DC_Adventures
Page fetched! https://en.wikipedia.org//wiki/DC_Heroes
Page fetched! https://en.wikipedia.org//wiki/DC_Universe_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/De_Profundis_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dead_Friend:_A_Game_of_Necromancy
Page fetched! https://en.wikipedia.org//wiki/Dead_Inside_(game)
Page fetched! https://en.wikipedia.org//wiki/Dead_Reign
Page fetched! https://en.wikipedia.org//wiki/Deadlands:_Hell_on_Earth
Page fetched! https://en.wikipedia.org//wiki/Deadlands:_Lost_Colony
Page fetched! https://en.wikipedia.org//wiki/Deadlands
Page fetched! https://en.wikipedia.org//wiki/Deathwatch_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Deliria
Page fetched! https://en.wikipedia.org//wiki/Delta_Force:_America_Strikes_Back!
Page fetched! https://en.wikipedia.org//wiki/Delta_Green
Page fetched! https://en.wikipedia.org//wiki/Degenesis
Page fetched! https://en.wikipedia.org//wiki/Demon_City_Shinjuku_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Demon_Hunters_Role_Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Demon:_The_Fallen
Page fetched! https://en.wikipedia.org//wiki/Deryni_Adventure_Game
Page fetched! https://en.wikipedia.org//wiki/Dialect_(game)
Page fetched! https://en.wikipedia.org//wiki/Diana:_Warrior_Princess
Page fetched! https://en.wikipedia.org//wiki/Diaspora_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Die_(comics_and_role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dinky_Dungeons
Page fetched! https://en.wikipedia.org//wiki/Dinosaur_Planet:_Broncosaurus_Rex
Page fetched! https://en.wikipedia.org//wiki/Diomin
Page fetched! https://en.wikipedia.org//wiki/Do:_Pilgrims_of_the_Flying_Temple
Page fetched! https://en.wikipedia.org//wiki/The_Doctor_Who_Role_Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Doctor_Who_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Time_Lord_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dog_Eat_Dog_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dogs_in_the_Vineyard
Page fetched! https://en.wikipedia.org//wiki/Domination_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dominion_Rules
Page fetched! https://en.wikipedia.org//wiki/The_Dominion_Tank_Police_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Donjon_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Don%27t_Look_Back_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Don%27t_Rest_Your_Head
Page fetched! https://en.wikipedia.org//wiki/Drac%C3%AD_doupe
Page fetched! https://en.wikipedia.org//wiki/Dragon_Age_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dragonlance:_Fifth_Age
Page fetched! https://en.wikipedia.org//wiki/Dragon_Lords_of_Melnibon%C3%A9
Page fetched! https://en.wikipedia.org//wiki/DragonMech
Page fetched! https://en.wikipedia.org//wiki/DragonQuest
Page fetched! https://en.wikipedia.org//wiki/DragonRaid
Page fetched! https://en.wikipedia.org//wiki/Dragonroar
Page fetched! https://en.wikipedia.org//wiki/Dragonstar_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dragon_Storm_(game)
Page fetched! https://en.wikipedia.org//wiki/Dragon_Warriors
Page fetched! https://en.wikipedia.org//wiki/Drakar_och_Demoner
Page fetched! https://en.wikipedia.org//wiki/Dread_RPG
Page fetched! https://en.wikipedia.org//wiki/Dread:_The_First_Book_of_Pandemonium
Page fetched! https://en.wikipedia.org//wiki/Dream_Askew,_Dream_Apart
Page fetched! https://en.wikipedia.org//wiki/Dream_Park:_The_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Dresden_files_rpg#Role_playing_game
Page fetched! https://en.wikipedia.org//wiki/Droids_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dune:_Chronicles_of_the_Imperium
Page fetched! https://en.wikipedia.org//wiki/Dungeons_%26_Dragons
Page fetched! https://en.wikipedia.org//wiki/Dungeon_Crawl_Classics
Page fetched! https://en.wikipedia.org//wiki/Dungeon_Squad
Page fetched! https://en.wikipedia.org//wiki/Dungeon_World
Page fetched! https://en.wikipedia.org//wiki/Durance_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Dust_Devils_(game)
Page fetched! https://en.wikipedia.org//wiki/The_Dying_Earth_Roleplaying_Game
Page fetched! https://en.wikipedia.org//wiki/Dzikie_Pola_(RPG)
Page fetched! https://en.wikipedia.org//wiki/EABA
Page fetched! https://en.wikipedia.org//wiki/Earth_2020
Page fetched! https://en.wikipedia.org//wiki/Earthdawn
Page fetched! https://en.wikipedia.org//wiki/Eat_the_Reich
Page fetched! https://en.wikipedia.org//wiki/Eclipse_Phase
Page fetched! https://en.wikipedia.org//wiki/Ehdrigohr
Page fetched! https://en.wikipedia.org//wiki/El-Hazard_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Eldritch_Role-Playing_System
Page fetched! https://en.wikipedia.org//wiki/Element_Masters
Page fetched! https://en.wikipedia.org//wiki/Elfquest_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Elfs_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Elric!
Page fetched! https://en.wikipedia.org//wiki/Empire_of_the_Petal_Throne
Page fetched! https://en.wikipedia.org//wiki/En_Garde!
Page fetched! https://en.wikipedia.org//wiki/The_End_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Enforcers_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Engel_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Eon_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/The_Esoterrorists
Page fetched! https://en.wikipedia.org//wiki/Espionage!
Page fetched! https://en.wikipedia.org//wiki/Eternal_Soldier
Page fetched! https://en.wikipedia.org//wiki/Etherscope
Page fetched! https://en.wikipedia.org//wiki/The_Everlasting_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/EverQuest_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Everway
Page fetched! https://en.wikipedia.org//wiki/Ex_Machina_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Exalted_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Exodus:_Post_Apocalyptic_RPG
Page fetched! https://en.wikipedia.org//wiki/Expendables_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/The_Extraordinary_Adventures_of_Baron_Munchausen
Page fetched! https://en.wikipedia.org//wiki/Fading_Suns
Page fetched! https://en.wikipedia.org//wiki/Fabula_Ultima
Page fetched! https://en.wikipedia.org//wiki/Fanhunter,_el_juego_de_rol_%C3%A9picodecadente
Page fetched! https://en.wikipedia.org//wiki/Spycraft_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Fantasy_Earth:_Basic_Rules
Page fetched! https://en.wikipedia.org//wiki/Fantasy_Hero
Page fetched! https://en.wikipedia.org//wiki/The_Fantasy_Trip
Page fetched! https://en.wikipedia.org//wiki/Fantasy_Wargaming
Page fetched! https://en.wikipedia.org//wiki/Farscape_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/F.A.T.A.L.
Page fetched! https://en.wikipedia.org//wiki/FATE_RPG
Page fetched! https://en.wikipedia.org//wiki/Fate_of_the_Norns
Page fetched! https://en.wikipedia.org//wiki/Fates_Worse_Than_Death_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/F%27Dech_Fo%27s_Tomb
Page fetched! https://en.wikipedia.org//wiki/Fear_Itself_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Feng_Shui_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Fiasco_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Field_Guide_to_Encounters
Page fetched! https://en.wikipedia.org//wiki/Field_Guide_to_Memory
Page fetched! https://en.wikipedia.org//wiki/Fifth_Cycle
Page fetched! https://en.wikipedia.org//wiki/Fighting_Fantasy:_The_Introductory_Role-Playing_Game
Page fetched! https://en.wikipedia.org//wiki/Fireborn
Page fetched! https://en.wikipedia.org//wiki/Firefly_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Flash_Gordon_%26_the_Warriors_of_Mongo
Page fetched! https://en.wikipedia.org//wiki/Flashing_Blades
Page fetched! https://en.wikipedia.org//wiki/For_the_Queen_(game)
Page fetched! https://en.wikipedia.org//wiki/Forbidden_Kingdoms
Page fetched! https://en.wikipedia.org//wiki/Forbidden_Lands
Page fetched! https://en.wikipedia.org//wiki/Forgotten_Futures
Page fetched! https://en.wikipedia.org//wiki/Freedom_Fighters_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Fringeworthy
Page fetched! https://en.wikipedia.org//wiki/FTL:2448
Page fetched! https://en.wikipedia.org//wiki/FUDGE
Page fetched! https://en.wikipedia.org//wiki/Furry_Pirates
Page fetched! https://en.wikipedia.org//wiki/Future_Worlds
Page fetched! https://en.wikipedia.org//wiki/Fuzion
Page fetched! https://en.wikipedia.org//wiki/A_Game_of_Thrones_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Gamma_World
Page fetched! https://en.wikipedia.org//wiki/Gangbusters_(role-playing_game)
Page fetched! https://en.wikipedia.org//wiki/Gangster!

In [254]:
games_df[~games_df['description'].isna()].to_csv('test_scrape.csv', index=False)

In [248]:
games_df

,game,link,publisher,system,release_year,setting,description
0,13th Age,/wiki/13th_Age,Pelgrane Press,D20 System,2013,High fantasy,13th Age is a d20 fantasy role-playing game de...
1,The 23rd Letter,/wiki/The_23rd_Letter,Crucible Design,,1996,,This is a list of notable tabletop role-playin...
2,2300 AD,/wiki/2300_AD,Game Designers' Workshop,,1989,Hard science fiction,"The tabletop game 2300 AD, originally titled T..."
3,3D&T,/wiki/3D%26T,Editora Talismã (formerly Trama Editorial),,1994,,"3DeT, formerly known as 3D&T or Defensores de ..."
4,7th Sea (role-playing game),/wiki/7th_Sea_(role-playing_game),Alderac Entertainment Group,D20 System,"1999, 2016",Pirate,"7th Sea is a ""swashbuckling and sorcery""-theme..."
...,...,...,...,...,...,...,...
782,Year of the Phoenix,/wiki/Year_of_the_Phoenix,Fantasy Games Unlimited,,1986,,Year of the Phoenix is a science-fiction role-...
783,Ysgarth,/wiki/Ysgarth,Ragnarok Games,,1979,,Ysgarth is a fantasy role-playing game publish...
784,The Zorcerer of Zo,/wiki/The_Zorcerer_of_Zo,Atomic Sock Monkey Press,,2006,Fairy tales,The Zantabulous Zorcerer of Zo is a fairy tale...
785,Zweihänder (role-playing game),/wiki/Zweih%C3%A4nder_(role-playing_game),Grim & Perilous Studios,,2017,,Zweihänder Grim & Perilous RPG or Zweihänder i...
786,Paranormal Order RPG,None,Jambô Editora,,2022,Urban Fantasy,None